name: Update game manifests

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-scripts-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create generated folder
        run: mkdir -p $(pwd)/scripts/generated

      - name: Move to generated
        run: |
          mv $(pwd)/hk4e_global.json $(pwd)/hkrpg_global.json $(pwd)/nap_global.json $(pwd)/bh3_global.json $(pwd)/wuwa_global.json $(pwd)/pgr_global.json $(pwd)/scripts/generated/

      - name: Run all scripts
        run: |
          echo "Current working directory: $(pwd)"
          echo "Scripts to run:"
          ls -lh $(pwd)/scripts/*.js
          for script in $(pwd)/scripts/*.js; do
            echo "======================================"
            echo "Running script: $script"
            echo "--------------------------------------"
            node "$script" append
            status=$?
            if [ $status -eq 0 ]; then
              echo "Script $script completed successfully."
            else
              echo "Script $script failed with exit code $status."
            fi
            echo "======================================"
            echo
          done

      - name: Fix hkrpg devs being goobers
        run: |
          sed -i '0,/DOWNLOAD_MODE_FILE/{s/DOWNLOAD_MODE_FILE/DOWNLOAD_MODE_CHUNK/}' $(pwd)/scripts/generated/hkrpg_global.json

      - name: Move generated JSONs to root
        run: |
          mv $(pwd)/scripts/generated/*.json $(pwd)/

      - name: Check for changes
        id: git-diff
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $(pwd)/*.json
          git diff --cached --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated: Update game manifests"
          branch: "game-manifests/update-${{ github.run_id }}"
          base: main
          title: "Automated: Update game manifests"
          body: "Review this PR to merge updated game manifests."
